server:
  port: 0

spring:
  application:
    name: book-service #microservices registers to eureka with the app name
  h2:
    console:
      path: /h2-console
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
