server:
  port: 0 #random bir port verilebilir, diğer servisler eureka üzerinden ulaşacağı için hiçbir sorun yoktur
          #sabit bir port verilirse eğer (örneğin 8081) bu servis bir kez daha çalıştırılamaz, port çakışması yaşanır

spring:
  application:
    name: book-service #microservices registers to eureka with the app name
  h2:
    console:
      path: /h2-console
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka} #env varsa kullan yoksa default olarak 8761/eureka'yı kullan
grpc:
  server:
    port: 9892
